#!/bin/sh
EDITOR=nvim
VISUAL=nvim
PICO_SDK_PATH=~/Programming/pico/pico-sdk

# mouse sensivity
xsetroot -cursor_name left_ptr       
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" -0.4
xinput --set-prop pointer:"Razer Razer DeathAdder Elite" \
                          "libinput Accel Speed" -0.72

# unitl I fix the touchpad
xinput set-prop 15 "Device Enabled" 0

# graphics tablet
xsetwacom --set "Wacom Intuos S 2 Pen stylus" MapToOutput 1920x1080+1920+0

