#!/bin/sh
EDITOR=nvim
VISUAL=nvim

# mouse sensivity
xsetroot -cursor_name left_ptr       
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" -0.4
xinput --set-prop pointer:"Razer Razer DeathAdder Elite" \
                          "libinput Accel Speed" -0.72

# graphics tablet
xsetwacom --set "Wacom Intuos S 2 Pen stylus" MapToOutput 1920x1080+1920+0

